# Generated by Django 5.0.1 on 2024-01-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('price_in', models.IntegerField()),
                ('price_out', models.IntegerField()),
            ],
        ),
    ]
