# Generated by Django 5.0.1 on 2024-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.CharField(choices=[('1', 'Szórakoztató elektronika'), ('2', 'Háztartási gép'), ('3', 'Televízió'), ('4', 'Mobiltelefon'), ('5', 'Fényképezőgép'), ('6', 'Nincs beállítva')], default=6, max_length=50),
        ),
    ]
