# Generated by Django 5.0.1 on 2024-02-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.good')),
            ],
        ),
    ]
