# Generated by Django 5.0.1 on 2024-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_good_discount_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
