# Generated by Django 5.0.1 on 2024-02-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_order_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_done',
        ),
    ]
