# Generated by Django 5.0.1 on 2024-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='photo',
            field=models.ImageField(blank=True, upload_to='goods'),
        ),
    ]
